# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andre's blog
email: meireles.andre@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog of Andre Meireles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _battlemage
github_username:  andre-meireles

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
# theme: minima
plugins:
  - jekyll-feed

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Site owner
author:
  name: Andre Meireles
  avatar: profile_photo.jpg
  bio: "Software developer at Amazon; helping make homes smarter with Alexa. Opinions my own."
  email: meireles.andre@outlook.com
  disqus-shortname: #username
  twitter: _battlemage
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: andre-meireles
  stackoverflow: #username
  linkedin: andre-meireles-05a9b19a
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
